---
- name: Precaution clean up before setup
  include_tasks: cleanup.yml

- name: Include machines variables
  include_vars: machines.yml

- name: Install required plugins
  include_tasks: install_plugin.yml

- block:
    - name: Create virtual machines
      include_tasks: create_vm.yml

    - name: Run Cloyster setup
      include_tasks: run_cloyster.yml
  rescue:
    - name: Set trigger to avoid final cleanup
      set_fact:
        skip_final_cleanup: true

- name: Clean up after setup
  include_tasks: cleanup.yml
  when: cleanup_needed and not skip_final_cleanup | default(false)

- name: Check for failure
  fail: msg="Setup failed"
  when: skip_final_cleanup | default(false)
